sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: develop
  persistence:
    config:
      enabled: true
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Sonarr
        hajimari.io/icon: file-document
      hosts:
        - host: &host sonarr.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: sonarr-tls-certificate
          hosts:
            - *host
