kind: Service
apiVersion: v1
metadata:
  name: switch1
  namespace: external-ingress
spec:
  type: ExternalName
  externalName: switch1-backend.tribz.cloud
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  switch1
  namespace: external-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: switch1
    hajimari.io/icon: multimedia
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - switch1.tribz.cloud
      secretName: switch1-tls-certificate
  rules:
    - host: switch1.tribz.cloud
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: switch1
                port:
                  number: 80