elasticsearch:
  volumeClaimTemplate:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  extraEnvs:
    - name: TZ
      value: Europe/Zurich
  replicas: 1
  minimumMasterNodes: 1
  antiAffinity: "soft"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: elasticearch
      hajimari.io/icon: multimedia
    className: "nginx"
    pathtype: ImplementationSpecific
    hosts:
      - host: &host elasticsearch.tribz.cloud
        paths:
          - path: /
    tls:
     - secretName: elasticsearch-tls-certificate
       hosts:
         - *host
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
  resources:
    requests:
      cpu: "100m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"