grocy:
  env:
    TZ: Europe/Zurich
  persistence:
   config:
     enabled: true
     mountPath: "/config"
     size: 1Gi
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Grocy
        hajimari.io/icon: home
      hosts:
        - host: &host grocy.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: grocy-tls-certificate
          hosts:
            - *host
  postgresql:
    volumeClaimTemplates:
      db:
        enabled: true
        mountPath: "/bitnami/postgresql"
        size: 10Gi