app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.*
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host homepage.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Popular:
            - Matrix:
                href: https://chat.tribz.cloud
                description: Chat client
                icon: element.svg
            - Jellyfin:
                href: https://jellyfin.tribz.cloud
                description: Media system (movies, music, etc.)
                icon: jellyfin.svg
            - Jellyseerr:
                href: https://jellyseerr.tribz.cloud
                description: Request media
                icon: jellyseerr.svg
          - Management:
            - Prowlarr:
                href: https://prowlarr.tribz.cloud
                description: Indexer manager
                icon: prowlarr.svg
            - Radarr:
                href: https://radarr.tribz.cloud
                description: Movie manager
                icon: radarr.svg
            - Sonarr:
                href: https://sonarr.tribz.cloud
                description: TV show manager
                icon: sonarr.svg
          - Development:
            - Gitea:
                href: https://git.tribz.cloud
                description: Git forge
                icon: gitea.svg
            - ArgoCD:
                href: https://argocd.tribz.cloud
                description: Continuous deployment
                icon: argocd.svg
            - Grafana:
                href: https://grafana.tribz.cloud
                description: Observability dashboards
                icon: grafana.svg
          - Utilities:
            - Speedtest:
                href: https://speedtest.tribz.cloud
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Public homelab repository:
              - href: https://github.com/gibute/homelab
                icon: github.svg