apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-system-matrix-alertmanager
  labels:
    app: matrix-alertmanager
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: matrix-alertmanager
  template:
    metadata:
      labels:
        app: matrix-alertmanager
    spec:
      containers:
      - name: matrix-alertmanager
        image: jaywink/matrix-alertmanager:latest
        ports:
        - containerPort: 3000
        env:
          - name: APP_PORT
            value: "3000"
          - name: APP_ALERTMANAGER_SECRET
            value: veryverysecretkeyhere
          - name: MATRIX_HOMESERVER_URL
            value: https://matrix.tribz.cloud
          - name: MATRIX_ROOMS
            value: 'matrix/!SJUyGAU028lzEpIb:matrix.tribz.cloud'
          - name: MATRIX_TOKEN
            value: 69jaaK87SJ4-PL6PSkrvXkD_XaW2EcRxj-Dc9JNfN2s
          - name: MATRIX_USER
            value: botdarr
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-system-matrix-alertmanager
spec:
  selector:
    app.kubernetes.io/instance: monitoring-system
    app.kubernetes.io/name: matrix-alertmanager
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000