# kube-prometheus-stack:
grafana:
  adminPassword: admin
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Grafana
      hajimari.io/icon: chart-bar
    hosts:
      - &host grafana.tribz.cloud
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.loki:3100
  envFromSecret: grafana-secrets
  grafana.ini:
    server:
      root_url: https://grafana.tribz.cloud
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      name: Dex
      client_id: grafana-sso
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://dex.tribz.cloud/auth
      token_url: https://dex.tribz.cloud/token
      api_url: https://dex.tribz.cloud/userinfo
prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
alertmanager:
  config:
    route:
      routes:
        - receiver: "null"
          matchers:
            - alertname =~ "InfoInhibitor|Watchdog"
        - receiver: 'matrix'
          continue: true
    receivers:
      - name: "null"  # Add this to your config as well
      - name: 'matrix'
        webhook_configs:
        - url: 'http://monitoring-system-matrix-alertmanager.monitoring-system/alerts?secret=veryverysecretkeyhere'
          send_resolved: true
kubeApiServer:
  enabled: true
kubeControllerManager:
  enabled: true
  endpoints:
  - 192.168.1.14
  - 192.168.1.18
  - 192.168.1.21
kubeScheduler:
  enabled: true
  endpoints:
  - 192.168.1.14
  - 192.168.1.18
  - 192.168.1.21
kubeProxy:
  enabled: true
  endpoints:
  - 192.168.1.14
  - 192.168.1.18
  - 192.168.1.21
kubeEtcd:
  enabled: true
  endpoints:
  - 192.168.1.14
  - 192.168.1.18
  - 192.168.1.21
  service:
    enabled: true
    port: 2381
    targetPort: 2381