core:
  k3s:
    enabled: true
  controller:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: NeuVector
        hajimari.io/icon: train-car-container
      host: neuvector.tribz.cloud
      tls: true
      secretName: neuvector-tls-certificate
    pvc:
      enabled: true
      # accessModes:
      #   - ReadWriteMany
      # storageClass:
      capacity: 10Gi
