core:
  k3s:
    enabled: true
  controller:
    pvc:
      enabled: true
      # accessModes:
      #   - ReadWriteMany
      # storageClass:
      capacity: 2Gi
  manager:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: NeuVector
        hajimari.io/icon: train-car-container
      host: neuvector.tribz.cloud
      tls: true
      secretName: neuvector-tls-certificate
  enforcer:
    resources: 
      limits:
        cpu: 1000m
        memory: 3072Mi
      requests:
        cpu: 500m
        memory: 1024Mi