apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: F:\_VSCodeWorkspace\kompose\kompose.exe convert -c -f F:\_VSCodeWorkspace\kompose\seafilecompose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: seafile
  name: seafile
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: seafile
status:
  loadBalancer: {}
