keycloak:
  domain: tribz.cloud
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Keycloak
      hajimari.io/icon: git
    ingressClassName: nginx
    hostname: keycloak.tribz.cloud
    tls: true
  postgresql:
    auth:
      password: "pass"
  externalDatabase:
    password: "pass"
  # extraEnvVars:
  #   - name: KC_HOSTNAME_ADMIN_URL
  #     value: https://keycloak.tribz.cloud
  proxy: reencrypt
  auth:
    adminUser: admin