keycloak:
  domain: tribz.cloud
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Keycloak
      hajimari.io/icon: git
    ingressClassName: nginx
    hostname: keycloak.tribz.cloud
    tls: true
  postgresql:
    auth:
      password: "pass"
  externalDatabase:
    password: "pass"
  extraEnvVars:
    - name: KEYCLOAK_ADMIN
      value: user
  proxy: reencrypt
  auth:
    adminUser: user