graylog:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: "5Gi"
    geoip:
      enabled: true
      ## If true, mmdbUri points to the URI where to find the DB
      # https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
      mmdbUri: ""
    rootUsername: "admin"
    rootPassword: "admin"

    rootTimezone: "Europe/Zurich"