graylog:
  elasticsearch:
    ## Major version of the Elasticsearch version used.
    ## It is required by Graylog 4. See https://docs.graylog.org/en/4.0/pages/configuration/elasticsearch.html#available-elasticsearch-configuration-tunables
    version: "7"
    ## List of Elasticsearch hosts Graylog should connect to.
    ## Need to be specified as a comma-separated list of valid URIs for the http ports of your elasticsearch nodes.
    ## If one or more of your elasticsearch hosts require authentication, include the credentials in each node URI that
    ## requires authentication.
    ##
    # hosts: http://elasticsearch-client.graylog.svc.cluster.local:9200
    hosts: http://elasticsearch-master.elasticsearch.svc.cluster.local:9200
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: "5Gi"
  geoip:
    enabled: true
    ## If true, mmdbUri points to the URI where to find the DB
    # https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
    mmdbUri: ""
  rootUsername: "admin"
  rootPassword: "admin"
  rootTimezone: "Europe/Zurich"
tags:
  # If true, this chart will install Elasticsearch from requirement dependencies
  install-elasticsearch: false
elasticsearch:
  volumeClaimTemplate:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  extraEnvs:
    - name: TZ
      value: Europe/Zurich
  replicas: 1
  minimumMasterNodes: 1
  antiAffinity: "soft"
  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"
  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"
