graylog:
  graylog: 
    elasticsearch:
      version: "7"
      hosts: "https://elasticsearch.tribz.cloud"
      uriSSL: true
    geoip:
      enabled: true
      mmdbUri: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=XRWrq0GbEsyJP012&suffix=tar.gz"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: "5Gi"
    rootUsername: "admin"
    rootPassword: "adminadminadminadmin"
    rootTimezone: "Europe/Zurich"

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: graylog
        hajimari.io/icon: multimedia
      ingressClassName: "nginx"
      hosts:
        - &host graylog.tribz.cloud
      tls:
        - secretName: graylog-tls-certificate
          hosts:
            - *host
      pathType: Prefix
      path: /
tags:
  install-elasticsearch: false