graylog:
  graylog: 
    input:
      udp:
        service:
          name: graylog-syslog-udp
          type: ClusterIP
        ports:
          - name: syslogudp
            port: 1514
    elasticsearch:
      version: "7"
      hosts: "http://elasticsearch-master.elasticsearch.svc.cluster.local:9200"
      # uriSSL: true
    geoip:
      enabled: true
      mmdbUri: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=XRWrq0GbEsyJP012&suffix=tar.gz"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: "5Gi"
    rootUsername: "admin"
    rootPassword: "adminadminadminadmin"
    rootTimezone: "Europe/Zurich"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: graylog
        hajimari.io/icon: multimedia
      ingressClassName: "nginx"
      hosts:
        - &host graylog.tribz.cloud
      tls:
        - secretName: graylog-tls-certificate
          hosts:
            - *host
      pathType: Prefix
      path: /
    externalUri: https://graylog.tribz.cloud
  resources:
    limits:
      cpu: "1"
    requests:
      cpu: "50m"
      memory: "512Mi"
tags:
  install-elasticsearch: false
  install-opensearch: false