guacamole-client:
  env:
    TZ: Europe/Zurich
    GUACD_HOSTNAME: guacamole-guacd.guacamole
  persistence:
    initdbdata:
      enabled: true
      mountPath: "/initdbdata"
      size: 10Gi
    # Both temphack and temphackalso will be removed on the next image release
    temphack:
      enabled: true
      mountPath: "/opt/guacamole/postgresql-hack"
      size: 10Gi
    temphackalso:
      enabled: true
      mountPath: "/opt/guacamole/postgresql"
      size: 10Gi
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Guacamole
        hajimari.io/icon: remote-desktop
        nginx.ingress.kubernetes.io/app-root: /guacamole
      hosts:
        - host: &host guacamole.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: guacamole-tls-certificate
          hosts:
            - *host
  postgresql:
    volumeClaimTemplates:
      db:
        enabled: true
        mountPath: "/bitnami/postgresql"
        size: 10Gi
