guacamole:
  # env:
  #   TZ: Europe/Zurich
  #   GUACD_HOSTNAME: guacamole-guacd.guacamole
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Guacamole
      hajimari.io/icon: remote-desktop
      nginx.ingress.kubernetes.io/app-root: /guacamole
    hosts:
      - host: &host guacamole.tribz.cloud
        paths:
          - /
            # pathType: Prefix
    tls:
      - secretName: guacamole-tls-certificate
        hosts:
          - *host
  # postgresql:
    # volumeClaimTemplates:
    #   db:
    #     enabled: true
    #     mountPath: "/bitnami/postgresql"
    #     size: 2Gi
postgresql:
  auth:
    username: guacamole
    postgresPassword: password
    database: guacamole