apiVersion: apps/v1
kind: Deployment
metadata:
  name: evosc
  labels:
    app: evosc
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: evosc
  template:
    metadata:
      labels:
        app: evosc
    spec:
      initContainers:
      - name: evosc-datainit
        image: evotm/evosc:latest
        command: ["/bin/sh", "-c"]
        args:
          - echo starting datainit;
            ls -la /controller;
            ls -la /datainit;
            if [ -d /datainit/config ];
              then echo already preseeded;
              else cp -r /controller/. /datainit;
            fi;
            ls -la /datainit;
            echo done;
        volumeMounts:
        - mountPath: /datainit
          name: evosc-config
        securityContext:
          runAsUser: 9999
          runAsGroup: 9999
          privileged: true
      containers:
        - name: evosc
          image: evotm/evosc:latest
          command: ["/bin/sh", "-c"]
          args: 
          # - "touch /controller/config/default/evosc.config.json && php esc run"
          # first run: then do php esc run manually
          - "touch /controller/config/default/evosc.config.json && sleep infinity"
          env:
            - name: TZ
              value: Europe/Zurich
            - name: MASTER_LOGIN
              value: YourMasterAdminIdIThink
            - name: DB_HOST
              value: trackmania-mariadb.trackmania.svc.cluster.local:3306
            - name: DB_NAME
              value: evosc
            - name: DB_USER
              value: evosc
            - name: DB_PASSWORD
              value: evosc
            - name: RPC_IP
              value: server
            - name: RPC_LOGIN
              value: SuperAdmin
            - name: RPC_PASSWORD
              value: SuperAdmin
          # livenessProbe:
          #   exec:
          #     command:
          #       - pgrep -x php || exit 1
          #   failureThreshold: 3
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          volumeMounts:
          - mountPath: /controller
            name: evosc-config
          - mountPath: /server/UserData
            name: trackmania-serverdata
      volumes:
        - name: evosc-config
          persistentVolumeClaim:
           claimName: evosc-config
        - name: trackmania-serverdata
          persistentVolumeClaim:
           claimName: trackmania-serverdata
