apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackmania
  labels:
    app: trackmania
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: trackmania
  template:
    metadata:
      labels:
        app: trackmania
    spec:
      initContainers:
      - name: trackmania-datainit
        image: evotm/trackmania:latest
        command: ["/bin/sh", "-c"]
        args:
          - echo starting datainit;
            ls -la /server/UserData;
            ls -la /datainit;
            cp -r /server/UserData/. /datainit;
            ls -la /datainit;
            echo done;
        volumeMounts:
        - mountPath: /datainit
          name: trackmania-serverdata
      containers:
        - name: trackmania
          image: evotm/trackmania:latest
          # postStart:
          #   exec:
          #     command: ["/bin/sh", "-c", "cp "]
          env:
            - name: TZ
              value: Europe/Zurich
            - name: MASTER_LOGIN
              value: Phorgasmic
            - name: MASTER_PASSWORD
              value: v%tr7,)w?h5<p}5S
            - name: SERVER_NAME
              value: Ridiculous
            - name: XMLRPC_ALLOWREMOTE
              value: "true"
            - name: DISABLE_REPLAY_RECORDING
              value: "false"
            - name: SAVE_ALL_INDIVIDUAL_RUNS
              value: "false"
            # - name: FORCE_IP_ADDRESS
            #   value: "true"
          ports:
            - containerPort: 2350
              protocol: UDP
            - containerPort: 2350
            - containerPort: 5000
          livenessProbe:
            exec:
              command:
                - nc -z -v 127.0.0.1 5000 || exit 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /server/UserData
            name: trackmania-serverdata
      volumes:
        - name: trackmania-serverdata
          persistentVolumeClaim:
           claimName: trackmania-serverdata
