apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackmania
  labels:
    app: trackmania
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: trackmania
  template:
    metadata:
      labels:
        app: trackmania
    spec:
      containers:
        - name: trackmania
          image: evotm/trackmania:latest
          env:
            - name: TZ
              value: Europe/Zurich
            - name: MASTER_LOGIN
              value: YourMasterserverLogin
            - name: MASTER_PASSWORD
              value: YourMasterserverPassword
            - name: SERVER_NAME
              value: Ridiculous
            - name: XMLRPC_ALLOWREMOTE
              value: "true"
            - name: DISABLE_REPLAY_RECORDING
              value: "false"
            - name: SAVE_ALL_INDIVIDUAL_RUNS
              value: "false"
            # - name: FORCE_IP_ADDRESS
            #   value: "true"