apiVersion: apps/v1
kind: Deployment
metadata:
  name: evosc
  labels:
    app: evosc
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: evosc
  template:
    metadata:
      labels:
        app: evosc
    spec:
      containers:
        - name: evosc
          image: evotm/evosc:latest
          command: ["/bin/sh", "-c"]
          args: 
          - "touch /controller/config/default/evosc.config.json && entrypoint.sh && php esc run"
          env:
            - name: TZ
              value: Europe/Zurich
            - name: MASTER_LOGIN
              value: YourMasterAdminIdIThink
            - name: DB_HOST
              value: trackmania-mariadb.trackmania.svc.cluster.local
            - name: DB_NAME
              value: evosc
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: rootpassword
            - name: RPC_IP
              value: server
            - name: RPC_LOGIN
              value: SuperAdmin
            - name: RPC_PASSWORD
              value: SuperAdmin
          # livenessProbe:
          #   exec:
          #     command:
          #       - pgrep -x php || exit 1
          #   failureThreshold: 3
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 5
      #     volumeMounts:
      #     - mountPath: /controller
      #       name: evosc-controller
      # volumes:
      #   - name: evosc-controller
      #     persistentVolumeClaim:
      #      claimName: evosc-controller
