# Retainable storage for whole mediastack data

apiVersion: v1
kind: PersistentVolume
metadata:
  name: evosc-config
spec:
  storageClassName: longhorn
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: evosc-config
    namespace: trackmania