image:
  repository: seafileltd/seafile-mc
  tag: latest
  pullPolicy: IfNotPresent
env:
  TZ: Europe/Zurich
  DB_HOST: myseafile-mariadb
  SEAFILE_ADMIN_EMAIL: michi.zimmerli@gmail.com
  SEAFILE_ADMIN_PASSWORD: admin
  SEAFILE_SERVER_HOSTNAME: &host myseafile.tribz.cloud
  SEAFILE_SERVER_LETSENCRYPT: "false"
  TIME_ZONE: Europe/Zurich
  DB_ROOT_PASSWD:
    valueFrom:
      secretKeyRef:
        name: myseafile-mariadb
        key: mariadb-root-password
lifecycle:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true
  privileged: true
  runAsNonRoot: false
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
persistence:
  config:
    enabled: true
    size: 1Gi
  shared:
    enabled: true
    size: 1Gi
ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: MySeafile
      hajimari.io/icon: google-drive
      nginx.ingress.kubernetes.io/proxy-body-size: "10g"
    hosts:
      - host: *host
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: myseafile-tls-certificate
        hosts:
          - *host
service:
  main:
    ports:
      main:
        port: 80
        protocol: HTTP
probes:
  liveness:
    custom: true
    spec:
      initialDelaySeconds: 25
      httpGet:
        path: /
        port: 80

  readiness:
    custom: true
    spec:
      initialDelaySeconds: 25
      httpGet:
        path: /
        port: 80

  startup:
    custom: true
    spec:
      initialDelaySeconds: 25
      httpGet:
        path: /
        port: 80

mariadb:
  persistence:
    enabled: true
    size: 2Gi