paperless-ng:
  persistence:
    data:
      enabled: true
      mountPath: "/data"
      size: 2Gi
    consume:
      enabled: true
      mountPath: "/consume"
      size: 2Gi
    media:
      enabled: true
      mountPath: "/media"
      size: 2Gi
  env:
    TZ: Europe/Zurich
    PAPERLESS_URL: "https://paperless.tribz.cloud"
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Paperless
        hajimari.io/icon: file-document
      hosts:
        - host: &host paperless.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: paperless-tls-certificate
          hosts:
            - *host
  postgresql:
    volumeClaimTemplates:
      db:
        enabled: true
        mountPath: "/bitnami/postgresql"
        size: 2Gi
  redis:
    volumeClaimTemplates:
      data:
        enabled: true
        mountPath: "/bitnami/redis"
        size: 2Gi

