apiVersion: v1
kind: Namespace
metadata:
  name: tekton-triggers
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
    pod-security.kubernetes.io/enforce: privileged