apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - templates

helmCharts:
- name: mariadb
  repo: https://charts.bitnami.com/bitnami
  version: 11.4.2
  releaseName: trackmania
  namespace: trackmania
  valuesFile: values-mariadb.yaml
  includeCRDs: true