nextcloud:
  nextcloud:
    host: &host nextcloud.tribz.cloud
    username: admin
    password: changeme
  persistence:
    enabled: true
    # size: 5Gi
  metrics:
    enabled: true
  ingress:
    enabled: true
    # className: nginx
    # hosts:
    #   - *host
    tls:
      - secretName: nextcloud-tls-certificate
        hosts:
          - *host
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.tribz.cloud"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hajimari.io/appName: Nextcloud
      hajimari.io/icon: google-drive
      # nginx.ingress.kubernetes.io/proxy-body-size: "10g"
    # tls:
    #   - secretName: nextcloud-tls-certificate
    #     hosts:
    #       - nextcloud.tribz.cloud
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          username: nextcloud
          password: changeme
          database: nextcloud
    primary:
      persistence:
        enabled: true
        # size: 5Gi