vikunja:
  persistence:
    files:
      enabled: true
      mountPath: "/app/vikunja/files"
      size: 2Gi
  env:
    TZ: Europe/Zurich
    VIKUNJA_SERVICE_FRONTENDURL: "https://vikunja.tribz.cloud"
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Vikunja
        hajimari.io/icon: home
      hosts:
        - host: &host vikunja.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: vikunja-tls-certificate
          hosts:
            - *host
  postgresql:
    volumeClaimTemplates:
      db:
        enabled: true
        mountPath: "/bitnami/postgresql"
        size: 2Gi
  redis:
    volumeClaimTemplates:
      data:
        enabled: true
        mountPath: "/bitnami/redis"
        size: 2Gi

