longhorn:
  defaultSettings:
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    replicaAutoBalance: best-effort
    defaultDataLocality: best-effort
    backupTarget: nfs://192.168.1.3:/mnt/tank/k8s/nfs/longhorn-backup
  persistence:
    # If you have three or more nodes for storage, use 3; otherwise use 2
    defaultClassReplicaCount: 3  # TODO run DR test to see if we actually need 3
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Longhorn
      hajimari.io/icon: google-drive
    host: longhorn.tribz.cloud
    tls: true
    tlsSecret: longhorn-tls-certificate
      # - secretName: longhorn-tls-certificate
      #   hosts:
      #     - *host