longhorn:
  defaultSettings:
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    replicaAutoBalance: best-effort
    defaultDataLocality: best-effort
    backupTarget: nfs://truenas.tribz.cloud:/mnt/tank/k8s/nfs/longhorn-backup
  persistence:
    # If you have three or more nodes for storage, use 3; otherwise use 2
    defaultClassReplicaCount: 3  # TODO run DR test to see if we actually need 3
    defaultDataLocality: best-effort
    removeSnapshotsDuringFilesystemTrim: enabled
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Longhorn
      hajimari.io/icon: google-drive
    host: longhorn.tribz.cloud
    tls: true
    tlsSecret: longhorn-tls-certificate