qbittorrent:
  env:
    TZ: Europe/Zurich
  persistence:
    config:
      enabled: true
      mountPath: /config
      accessMode: ReadWriteOnce
      size: 1Gi
    downloads:
      enabled: true
      mountPath: /downloads
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: freenas-nfs-csi
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: qbittorrent
        hajimari.io/icon: file-document
      hosts:
        - host: &host qbittorrent.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: qbittorrent-tls-certificate
          hosts:
            - *host
radarr:
  env:
    TZ: Europe/Zurich
  image:
    repository: lscr.io/linuxserver/radarr
    tag: develop
  persistence:
    config:
      enabled: true
    downloads:
      enabled: true
      mountPath: /downloads
      existingClaim: mediastack-qbittorrent-downloads
    media:
      enabled: true
      mountPath: /media
      existingClaim: mediastack-jellyfin-media
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: radarr
        hajimari.io/icon: file-document
      hosts:
        - host: &host radarr.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: radarr-tls-certificate
          hosts:
            - *host
jellyfin:
  persistence:
    config:
      enabled: true
    media:
      enabled: true
      mountPath: /media
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: freenas-nfs-csi
      # retain: true needed eventually
  env:
    TZ: Europe/Zurich
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Jellyfin
        hajimari.io/icon: filmstrip
      hosts:
        - host: &host jellyfin.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *host

