prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: develop
  persistence:
    config:
      enabled: true
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: prowlarr
        hajimari.io/icon: file-document
      hosts:
        - host: &host prowlarr.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: prowlarr-tls-certificate
          hosts:
            - *host
