apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-discordbot
  labels:
    app: tts-discordbot
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tts-discordbot
  template:
    metadata:
      labels:
        app: tts-discordbot
    spec:
      containers:
      - name: tts-discordbot
        # image: core.harbor.tribz.cloud/homelab/tts-discordbot:latest
        image: core.harbor.tribz.cloud/homelab/discord-google-tts:latest
        env:
          - name: TZ
            value: "Europe/Zurich"
          # - name: DISCORD_ENABLE_TTS_CHANNELS
          #   value: "true"