apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Pipeline
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  # Service account
  - clusterrolebinding.yaml
