apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  labels:
    app: xmrig
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
        - name: xmrig
          image: metal3d/xmrig:6.18.0-1
          imagePullPolicy: IfNotPresent
          env:
            - name: POOL_USER
              value: 48d6wTGGi5pRtpYtmKcNtvYUUYqSpr8pFW79ZBX2bcCyBwaj2K3HVc2eJ9AXvTH6qVHz6rAe2814c1x4PvxrxcWB4jZs86f
            - name: POOL_PASS
              value: ""
              # valueFrom:
              #   secretKeyRef:
              #     name: {{ .Release.Name }}-pool-secret
              #     key: POOL_PASS
            - name: POOL_URL
              value: pool.supportxmr.com:5555
            - name: DONATE_LEVEL
              value: "0"
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 0
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              host:
              port: 3000
          readinessProbe:
            tcpSocket:
              host:
              port: 3000