apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  labels:
    app: xmrig
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
        - name: xmrig
          image: metal3d/xmrig:6.18.0-1
          imagePullPolicy: IfNotPresent
          env:
            - name: POOL_USER
              value: 48d6wTGGi5pRtpYtmKcNtvYUUYqSpr8pFW79ZBX2bcCyBwaj2K3HVc2eJ9AXvTH6qVHz6rAe2814c1x4PvxrxcWB4jZs86f
            - name: POOL_PASS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POOL_URL
              value: gulf.moneroocean.stream:10128
            - name: DONATE_LEVEL
              value: "0"
            # - name: PRIORITY
            #   value: "0"
            # - name: THREADS
            #   value: "4"
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "6144Mi"
              cpu: "2000m"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              host:
              port: 3000
          readinessProbe:
            tcpSocket:
              host:
              port: 3000