apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xmrig-pubkey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
  data:
    - secretKey: pubkey
      remoteRef:
        key: /monero
        property: pubkey
