apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xmrig-pubkey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        PUBKEY: {{` "{{ .pubkey }}" `}}
  data:
    - secretKey: token
      remoteRef:
        key: /monero
        property: pubkey
