apiVersion: v1
data:
  POOL_PASS: {{ .Values.worker.pass | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-pool-secret
  labels:
    app.kubernetes.io/name: {{ include "xmrig.name" . }}
    helm.sh/chart: {{ include "xmrig.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}