apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishtest-worker
  labels:
    app: worker
spec:
  replicas: 8
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: core.harbor.tribz.cloud/homelab/fishtest:latest
        env:
          - name: FISHTEST_USERNAME
            value: "Tribute"
          - name: FISHTEST_PASSWORD
            value: "FishTestsKubernetes123"
          - name: FISHTEST_CORES
            value: '1'
          - name: FISHTEST_MEMORY
            value: '1024'
