apiVersion: batch/v1
kind: Job
metadata:
  name: fishtest-worker
  labels:
    app: worker
spec:
  parallelism: 8
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
        image: core.harbor.tribz.cloud/homelab/fishtest:latest
        env:
          - name: FISHTEST_USERNAME
            value: "Tribute"
          - name: FISHTEST_PASSWORD
            value: "FishTestsKubernetes123"
          - name: FISHTEST_CORES
            value: "1"
          - name: FISHTEST_MEMORY
            value: "1024"
