apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: alpine:latest
          env:
            - name: TZ
              value: Europe/Zurich
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo starting init;
              apk add curl gcompat;
              curl -LO https://dl.k8s.io/v1.24.10/bin/linux/amd64/kubectl;
              chmod +x kubectl;
              mv ./kubectl /bin/kubectl;
              mkdir ~/.kube;
              echo "apiVersion: v1
              clusters:
              - cluster:
                  certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTnpBMU56STNNRFF3SGhjTk1qSXhNakE1TURjMU9ESTBXaGNOTXpJeE1qQTJNRGMxT0RJMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTnpBMU56STNNRFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRWDBNcXlReEhSOFN0c0Q0U0UzenYyNzRCYnROK21hOGRPNTM5WVZJUXAKUEl1N2RRTmFGT0wrZEtrWmhUcG51cTB6TFpaa3E2S2pKRU1oZS9BaS8vdzlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXI2TUdkamlRa2lyUm42bWVQd3MxClFLbFhGQ0l3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYWhIWmNYcEovaGdEMFU0Vkt0YStiYUJ6Y2NReG1MZlkKNU9rTGdZblMreHNDSVFDTmtOWkUzQzFZczFkQmFxUTJlZjYvRFRpcDg5QURuYTFCS0JNOFNqcVhiUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
                  server: https://192.168.1.200:6443
                name: default
              contexts:
              - context:
                  cluster: default
                  user: default
                name: default
              current-context: default
              kind: Config
              preferences: {}
              users:
              - name: default
                user:
                  client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJUVRGZDhQWUlpY0V3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOamN3TlRjeU56QTBNQjRYRFRJeU1USXdPVEEzTlRneU5Gb1hEVEl6TVRJdwpPVEEzTlRneU5Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKMHJQMXJVa0o4RlhTNnoKbDZkZ3l5UzM0SVQ4SDVJVFp2Zm4rcTd3dTdUZVhhc1FSdWdyNDdhdTUrUVE0WVJoclp5LzJXY1lnSG1Kb1ZCbgpRdThYU3I2alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUSt5c0dtaU5RTHBIQ2gxWTI4dFZnM29LT1RTREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlCZ09qaE1ZYTViQUM2aGRlTkNjMlN0TTdZU2RwSWd4czZJaUV3b3hWR1VNQUloQUtGL2p3cXRTMEs2bHdyTAorOXRFek1kM3lYZFoxcHM2SlZXM2ZQL2EwcnhqCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTnpBMU56STNNRFF3SGhjTk1qSXhNakE1TURjMU9ESTBXaGNOTXpJeE1qQTJNRGMxT0RJMApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTnpBMU56STNNRFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUVTM1UGd2citDY2dSWFdSbjlDNllyUEZsRk01dThUdWRyeDg3OGFiVHkKTU9pbXJreGJla0dkMERxKzd6TFduVndlL1FoOHcvM0JCU1F6L2JmbDlNazJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVBzckJwb2pVQzZSd29kV052TFZZCk42Q2prMGd3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYS92Y0dSM1JkaGg1YXMrUHJRVEZEdDN5QmVsTExBa00KMm53OE9rQ00zODBDSVFETGl4U2UxeHBuZXBlZWxJZkRkYWN1N2I3VmR6bHJNRStrSURSWDZKUVp5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
                  client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNEaVhOVW1wM2Qwa2FmaG5JcU85K0tEaGMxdGhwUUVRZ1NRL2w2UkNDWkFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFblNzL1d0U1Fud1ZkTHJPWHAyRExKTGZnaFB3ZmtoTm05K2Y2cnZDN3RONWRxeEJHNkN2agp0cTduNUJEaGhHR3RuTC9aWnhpQWVZbWhVR2RDN3hkS3ZnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
              " >~/.kube/config;
              curl -LO https://github.com/Huawei/eSDK_K8S_Plugin/releases/download/V3.2.1/eSDK_Huawei_Storage_Kubernetes_CSI_Plugin_V3.2.1_X86_64.zip;
              echo init done;
              sleep infinity;