apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: alpine:latest
          env:
            - name: TZ
              value: Europe/Zurich
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo starting init;
              apk add curl git;
              curl -LO https://dl.k8s.io/v1.24.10/bin/linux/amd64/kubectl;
              chmod +x kubectl;
              mv ./kubectl /bin/kubectl;
              mkdir ~/.kube;
              git clone https://github.com/Huawei/eSDK_K8S_Plugin.git;
              echo init done;
              sleep infinity;