apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      initContainers:
      - name: admin-init
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - echo starting init;
            apk add curl;
            curl -LO https://dl.k8s.io/release/v1.24.10/bin/linux/amd64/;
            chmod +x kubectl;
            mkdir -p ~/.local/bin;
            mv ./kubectl ~/.local/bin/kubectl;
            git clone https://github.com/Huawei/eSDK_K8S_Plugin.git;
            echo done;
      containers:
        - name: admin
          image: alpine:latest
          env:
            - name: TZ
              value: Europe/Zurich
          command: ["/bin/sh", "-c", "sleep infinity"]