- name: Ensure MetalLB namespace exist
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ metallb_namespace }}"
    state: present

- name: Create MetalLB addresspool base on network info
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'addresspool.yaml.j2') | from_yaml }}"
- name: Create MetalLB l2 advertisement
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'advertisement.yaml.j2') | from_yaml }}"

