apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sons-of-the-forest-steamcmd
spec:
  storageClassName: longhorn-retain
  # dataSource:
  #  name: pvc-f8469456-f44a-4ef8-806b-75e30db578a8
  #  kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi