apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloudadmin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
  data:
    - secretKey: pubkey
      remoteRef:
        key: /nextcloudadmin
        property: password
