apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediastack-botdarr
  labels:
    app: botdarr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: botdarr
  template:
    metadata:
      labels:
        app: botdarr
    spec:
      containers:
      - name: botdarr
        image: shayaantx/botdarr:latest
        env:
          - name: MAX_DOWNLOADS_TO_SHOW
            value: "100"
          - name: MAX_RESULTS_TO_SHOW
            value: "100"
          - name: SONARR_URL
            value: https://sonarr.tribz.cloud
          - name: SONARR_TOKEN
            value: "e318852e124c4d8dae1d7135d0d84194"
          - name: SONARR_DEFAULT_PROFILE
            value: Any
          - name: SONARR_PATH
            value: /data/media/sonarr/
          - name: SONARR_V4
            value: "yes"
          - name: RADARR_URL
            value: https://radarr.tribz.cloud
          - name: RADARR_TOKEN
            value: "7b5ae599d7374f1f9e77874a03d5107a"
          - name: RADARR_DEFAULT_PROFILE
            value: Any
          - name: RADARR_PATH
            value: /data/media/radarr/
          - name: MATRIX_ROOM
            value: '!VXlmMUbDdWUi226Z:matrix.tribz.cloud'
          - name: MATRIX_USERNAME
            value: botbotdarr
          - name: MATRIX_PASSWORD
            value: botbotdarr123
          - name: MATRIX_HOME_SERVER_URL
            value: https://matrix.tribz.cloud
        ports:
        - containerPort: 80
