# Retainable storage for whole mediastack data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediastack-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: freenas-nfs-csi-retain
  resources:
    requests:
      storage: 500Gi