# Retainable storage for whole mediastack data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mediastack-data
spec:
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: org.democratic-csi.nfs
    fsType: nfs
    volumeHandle: pv-mediastack-data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediastack-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-mediastack-data