apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mediastack-data
spec:
  volumeMode: Filesystem
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteOnce
  csi:
    driver: org.democratic-csi.nfs
    fsType: nfs
    volumeHandle: pv-mediastack-data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediastack-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: freenas-nfs-csi
  volumeName: pv-mediastack-data