apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediastack-jellyseerr
  labels:
    app: jellyseerr
spec:
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      volumes:
        - name: jellyseerr-config
          persistentVolumeClaim:
           claimName: jellyseerr-config
      containers:
      - name: jellyseerr
        image: fallenbagel/jellyseerr:latest
        env:
          - name: TZ
            value: Europe/Zurich
        ports:
        - containerPort: 5055
        volumeMounts:
          - mountPath: /app/config
            name: jellyseerr-config