apiVersion: v1
kind: Pod
metadata:
  name: "mediastack-nfs"
spec:
  # volumes:
  #   - name: data
  #     persistentVolumeClaim:
  #       claimName: mediastack-data
  containers:
  - name: mediastack-nfs
    env:
      - name: TZ
        value: Europe/Zurich
    image: rockylinux:9.0.20220720-minimal
    command: ["/bin/bash", "-c", "sleep infinity"]
    # volumeMounts:
    #   - mountPath: /data
    #     name: data
    securityContext:
      privileged: true