qbittorrent:
  env:
    TZ: Europe/Zurich
  persistence:
    media:
      enabled: true
      mountPath: /media
      accessMode: ReadWriteOnce
      size: 1Gi
    downloads:
      enabled: true
      mountPath: /downloads
      accessMode: ReadWriteOnce
      size: 5Gi
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: qbittorrent
        hajimari.io/icon: file-document
      hosts:
        - host: &host qbittorrent.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: qbittorrent-tls-certificate
          hosts:
            - *host