qbittorrent:
  env:
    TZ: Europe/Zurich
  settings:
    automaticPortSetup: true
  persistence:
    config:
      enabled: true
    media:
      enabled: true
      mountPath: /media
    downloads:
      enabled: true
      mountPath: /downloads
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: qbittorrent
        hajimari.io/icon: file-document
      hosts:
        - host: &host qbittorrent.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: qbittorrent-tls-certificate
          hosts:
            - *host