harbor:
  chartmuseum:
    revisionHistoryLimit: 3
  registry:
    revisionHistoryLimit: 3
  notary:
    server:
      revisionHistoryLimit: 3
  expose:
    type: ingress
    ingress:
      hosts:
        core: core.harbor.tribz.cloud
        notary: notary.harbor.tribz.cloud
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Harbor
        hajimari.io/icon: git
        nginx.ingress.kubernetes.io/proxy-body-size: "10g"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: harbor-tls-certificate
        notarySecretName: harbor-notary-tls-certificate
  externalURL: https://core.harbor.tribz.cloud
  updateStrategy:
    type: Recreate