graphite:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: graphite
      hajimari.io/icon: multimedia
    path: /
    hosts:
      - &host graphite.tribz.cloud
    tls:
    - secretName: graphite-tls-certificate
      hosts:
        - *host

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi

  timeZone: Europe/Zurich