pihole:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: PiHole
        hajimari.io/icon: google-drive
    hosts:
     - &host pihole.tribz.cloud
    tls:
      - secretName: pihole-tls-certificate
        hosts:
          - *host
  serviceDns:
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer
    sessionAffinity: None
    externalTrafficPolicy: Cluster
    ipFamilies:
      - IPv4
    ipFamilyPolicy: SingleStack
    allocateLoadBalancerNodePorts: true
    internalTrafficPolicy: Cluster
