pihole:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: PiHole
        hajimari.io/icon: google-drive
    hosts:
     - &host pihole.tribz.cloud
    tls:
      - secretName: pihole-tls-certificate
        hosts:
          - *host