apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ac-authserver
  name: ac-authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ac-authserver
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/azerothcore-wotlk-ac-network: "true"
        io.kompose.service: ac-authserver
    spec:
      containers:
        - env:
            - name: AC_CCACHE
              valueFrom:
                configMapKeyRef:
                  key: AC_CCACHE
                  name: azerothcore-wotlk-conf-dist-env-ac
            - name: AC_LOGIN_DATABASE_INFO
              value: ac-database;3306;root;password;acore_auth
            - name: AC_LOGS_DIR
              value: /azerothcore/env/dist/logs
            - name: AC_RESTARTER_BINFILE
              valueFrom:
                configMapKeyRef:
                  key: AC_RESTARTER_BINFILE
                  name: azerothcore-wotlk-conf-dist-env-ac
            - name: AC_RESTARTER_BINPATH
              valueFrom:
                configMapKeyRef:
                  key: AC_RESTARTER_BINPATH
                  name: azerothcore-wotlk-conf-dist-env-ac
            - name: AC_RESTARTER_WITHGDB
              valueFrom:
                configMapKeyRef:
                  key: AC_RESTARTER_WITHGDB
                  name: azerothcore-wotlk-conf-dist-env-ac
            - name: AC_TEMP_DIR
              value: /azerothcore/env/dist/temp
            - name: CSCRIPTS
              valueFrom:
                configMapKeyRef:
                  key: CSCRIPTS
                  name: azerothcore-wotlk-conf-dist-env-ac
            - name: CTYPE
              valueFrom:
                configMapKeyRef:
                  key: CTYPE
                  name: azerothcore-wotlk-conf-dist-env-ac
            - name: DATAPATH
              valueFrom:
                configMapKeyRef:
                  key: DATAPATH
                  name: azerothcore-wotlk-conf-dist-env-ac
            - name: USER_CONF_PATH
              valueFrom:
                configMapKeyRef:
                  key: USER_CONF_PATH
                  name: azerothcore-wotlk-conf-dist-env-ac
          image: acore/ac-wotlk-authserver:master
          # command: ["/bin/bash", "-c", "sleep infinity"]
          securityContext:
            fsGroup: 1000
          name: ac-authserver
          ports:
            - containerPort: 3724
              hostPort: 3724
              protocol: TCP
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /azerothcore/env/dist/etc
              name: ac-authserver-claim0
            - mountPath: /azerothcore/env/dist/logs
              name: ac-authserver-claim1
      restartPolicy: Always
      volumes:
        - name: ac-authserver-claim0
          persistentVolumeClaim:
            claimName: ac-authserver-claim0
        - name: ac-authserver-claim1
          persistentVolumeClaim:
            claimName: ac-authserver-claim1
status: {}
