apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ac-database
  name: ac-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ac-database
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/azerothcore-wotlk-ac-network: "true"
        io.kompose.service: ac-database
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: mysql:8.0
          livenessProbe:
            exec:
              command:
                - /usr/bin/mysql --user=root --password=$MYSQL_ROOT_PASSWORD --execute "SHOW DATABASES;"
            failureThreshold: 40
            periodSeconds: 5
            timeoutSeconds: 10
          name: ac-database
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              subPath: mysql
              name: ac-database
      restartPolicy: Always
      volumes:
        - name: ac-database
          persistentVolumeClaim:
            claimName: ac-database
status: {}
