apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      volumes:
        - name: ac-authserver-claim0
          persistentVolumeClaim:
            claimName: ac-authserver-claim0
        - name: ac-authserver-claim1
          persistentVolumeClaim:
            claimName: ac-authserver-claim1
      containers:
      - name: admin
        env:
          - name: TZ
            value: Europe/Zurich
        image: rockylinux:9.0.20220720-minimal
        command: ["/bin/bash", "-c", "sleep infinity"]
        volumeMounts:
          - mountPath: /ac-authserver-claim0
            name: ac-authserver-claim0
          - mountPath: /ac-authserver-claim1
            name: ac-authserver-claim1
        securityContext:
          privileged: true