apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- templates
- https://github.com/kubernetes-csi/external-snapshotter/client/config/crd/?ref=v6.2.1
- https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller/?ref=v6.2.1

helmCharts:
- name: k10
  repo: https://charts.kasten.io/
  version: 6.5.*
  releaseName: kasten-io
  namespace: kasten-io
  valuesFile: values.yaml
  includeCRDs: true