home-assistant:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Home-Assistant
        hajimari.io/icon: google-drive
        nginx.org/websocket-services: home-assistant
      hosts:
        - host: &host home-assistant.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: home-assistant-tls-certificate
          hosts:
            - *host
  postgresql:
    enabled: true
  persistence:
    config:
      enabled: true
      size: 2Gi