home-assistant:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Home-Assistant
        hajimari.io/icon: google-drive
        nginx.org/websocket-services: home-assistant
      hosts:
        - host: &host home-assistant.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: home-assistant-tls-certificate
          hosts:
            - *host
  postgresql:
    enabled: true
  initContainers:
    home-assistant-datainit:
      image: ghcr.io/home-assistant/home-assistant:2023.8.4
      # command: ["/bin/sh", "-c"]
      # args:
      #   - echo starting datainit;
      #     ls -la /server/UserData;
      #     ls -la /datainit;
      #     if [ -d /datainit/Config ];
      #       then echo already preseeded;
      #       else cp -r /server/UserData/. /datainit;
      #       cp /datainit/Maps/MatchSettings/default.txt /datainit/Maps/MatchSettings/maplist.txt;
      #     fi;
      #     ls -la /datainit;
      #     echo done;
      volumeMounts:
      - mountPath: /config
        name: config
  persistence:
    config:
      enabled: true
      size: 2Gi
    configfile:
      enabled: true
      name: home-assistant-configfile
      items:
        - key: configuration
          path: configuration.yaml
      type: configMap
      mountPath:  /config/configuration.yaml
      subPath: configuration.yaml
  configmap:
    configfile:
      enabled: true
      data:
        configuration: |
          # Loads default set of integrations. Do not remove.
          default_config:

          # Load frontend themes from the themes folder
          frontend:
          themes: !include_dir_merge_named themes

          automation: !include automations.yaml
          script: !include scripts.yaml
          scene: !include scenes.yaml
          http:
            server_host: 0.0.0.0
            ip_ban_enabled: true
            login_attempts_threshold: 5
            use_x_forwarded_for: true
            trusted_proxies:
              - 10.42.0.0/16
          
          # Database
          recorder:
            db_url: "postgresql://home-assistant:home-assistant@home-assistant-postgresql.home-assistant/home-assistant"
            db_retry_wait: 15 # Wait 15 seconds before retrying
            exclude:
              domains:
                - automation
                - updater
              entity_globs:
                - sensor.weather_*
              entities:
                - sun.sun # Don't record sun data
                - sensor.last_boot # Comes from 'systemmonitor' sensor platform
                - sensor.date
              event_types:
                - call_service # Don't record service calls
postgresql:
  auth:
    username: home-assistant
    password: home-assistant
    database: home-assistant