home-assistant:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Home-Assistant
        hajimari.io/icon: google-drive
        nginx.org/websocket-services: home-assistant
      hosts:
        - host: &host home-assistant.tribz.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: home-assistant-tls-certificate
          hosts:
            - *host
  postgresql:
    enabled: true
  persistence:
    config:
      enabled: true
      size: 2Gi
    configfile:
      enabled: true
      name: home-assistant-configfile
      items:
        - key: configuration
          path: configuration.yaml
      type: configMap
      mountPath:  /config/configuration.yaml
      subPath: configuration.yaml
  configmap:
    configfile:
      enabled: true
      data:
        configuration: |
          # Loads default set of integrations. Do not remove.
          default_config:

          # Load frontend themes from the themes folder
          frontend:
          themes: !include_dir_merge_named themes

          automation: !include automations.yaml
          script: !include scripts.yaml
          scene: !include scenes.yaml
          http:
            server_host: 0.0.0.0
            ip_ban_enabled: true
            login_attempts_threshold: 5
            use_x_forwarded_for: true
            trusted_proxies:
              - 10.42.0.0/16