apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metallb-system-prometheus
  namespace: metallb-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metallb-system-prometheus
  namespace: metallb-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metallb-system-prometheus
  namespace: metallb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metallb-system-prometheus
subjects:
  - kind: ServiceAccount
    name: monitoring-system-kube-pro-prometheus
    namespace: monitoring-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metallb-system-prometheus
  namespace: metallb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metallb-system-prometheus
subjects:
  - kind: ServiceAccount
    name: monitoring-system-kube-pro-prometheus
    namespace: monitoring-system