apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: k10-backup-nfs-pvc
spec:
   storageClassName: nfs
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 10Gi