apiVersion: v1
kind: PersistentVolume
metadata:
   name: k10-backup-nfs-pv-2
spec:
   capacity:
      storage: 10Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   storageClassName: nfs
   mountOptions:
      - hard
      - nfsvers=4.1
   nfs:
      path: /mnt/tank/k8s/nfs/k10-backup-2
      server: truenas.tribz.cloud