apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: driver.longhorn.io
kind: VolumeSnapshotClass
metadata:
  name: longhorn-snap-vsc-delete
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
parameters:
  type: snap 