k3s_version: v1.27.8+k3s2
k3s_config_file: /etc/rancher/k3s/config.yaml
k3s_token_file: /etc/rancher/node/password
k3s_service_file: /etc/systemd/system/k3s.service
k3s_server_config:
  disable:
    - local-storage
    - servicelb
    - traefik
  disable-cloud-controller: true
  secrets-encryption: true
  tls-san: k8s.tribz.cloud
  etcd-expose-metrics: true
  kube-controller-manager-arg:
  - "bind-address=0.0.0.0"
  kube-proxy-arg:
  - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
  - "bind-address=0.0.0.0"
  kubelet-arg:
  - "image-gc-high-threshold=50"
  - "image-gc-low-threshold=20"
k3s_agent_config:
  kubelet-arg:
  - "image-gc-high-threshold=50"
  - "image-gc-low-threshold=20"