apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

# resources:
#   - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml

helmCharts:
- name: metallb
  repo: https://metallb.github.io/metallb
  version: 0.*.*
  releaseName: metallb-system
  valuesFile: values.yaml
  includeCRDs: true

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: metallb-system-speaker-monitor-service
    patch: |-
      - op: replace
        path: "/spec/ports/0/name"
        value: "monitoring"
  - target:
      version: v1
      kind: Service
      name: metallb-system-controller-monitor-service
    patch: |-
      - op: replace
        path: "/spec/ports/0/name"
        value: "monitoring"
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: metallb-system-controller
    patch: |-
      - op: add
        path: "/rules
        value: 
            - verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
              apiGroups:
                - 'apiextensions.k8s.io'
              resources:
                - customresourcedefinitions