apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml

helmCharts:
- name: metallb
  repo: https://metallb.github.io/metallb
  version: 0.*.*
  releaseName: metallb-system
  namespace: metallb-system
  valuesFile: values.yaml
  includeCRDs: true

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: metallb-system-speaker-monitor-service
    patch: |-
      - op: replace
        path: "/spec/ports/0/name"
        value: "monitoring"