apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  labels:
    app: grocy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
        - name: grocy
          image: lscr.io/linuxserver/grocy:latest
          ports:
            - containerPort: 9283