apiVersion: apps/v1
kind: Deployment
metadata:
  name: palworld
  labels:
    app: palworld
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: palworld
  template:
    metadata:
      labels:
        app: palworld
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: name
              operator: In
              values:
              - metal1  
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: palworld
          resources:
            requests:
              memory: "6Gi"
              cpu: "3000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
          # securityContext:
          #   allowPrivilegeEscalation: true
            # runAsUser: 0
          image: kagurazakanyaa/palworld:latest
          env:
            - name: TZ
              value: Europe/Zurich
            - name: SERVER_NAME
              value: Biohazard
            - name: ADMIN_PASSWORD
              value: bioadmin
            # - name: SERVER_PASSWORD
            #   value: bioplayer
            - name: RCON_ENABLED
              value: "true"
            # - name: ALWAYS_UPDATE_ON_START
            #   value: "1"
          ports:
            - containerPort: 8211
              protocol: UDP
            # - containerPort: 27016
            #   protocol: UDP
            # - containerPort: 9700
            #   protocol: UDP
          # livenessProbe:
          #   exec:
          #     command:
          #       - nc -z -v 127.0.0.1 5000 || exit 1
          #   failureThreshold: 3
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          volumeMounts:
          - mountPath: /op/palworld/Pal/Saved
            name: palworld-game
      volumes:
        - name: palworld-game
          persistentVolumeClaim:
           claimName: palworld-game