apiVersion: v1
kind: Service
metadata:
  name: palworld
  namespace: palworld
spec:
  type: NodePort
  ports:
    - name: 8211-udp
      port: 8211
      protocol: UDP
      targetPort: 8211
      nodePort: 30001
    # - name: 27016-udp
    #   port: 27016
    #   protocol: UDP
    #   targetPort: 27016
    # - name: 9700-udp
    #   port: 9700
    #   protocol: UDP
    #   targetPort: 9700
  selector:
    app: palworld