apiVersion: apps/v1
kind: Deployment
metadata:
  name: sons-of-the-forest
  labels:
    app: sons-of-the-forest
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sons-of-the-forest
  template:
    metadata:
      labels:
        app: sons-of-the-forest
    spec:
      containers:
        - name: sons-of-the-forest
          image: jammsen/sons-of-the-forest-dedicated-server:latest
          env:
            - name: TZ
              value: Europe/Zurich
            - name: ALWAYS_UPDATE_ON_START
              value: 1
          ports:
            - containerPort: 8766
              protocol: UDP
            - containerPort: 27016
              protocol: UDP
            - containerPort: 9700
              protocol: UDP
          # livenessProbe:
          #   exec:
          #     command:
          #       - nc -z -v 127.0.0.1 5000 || exit 1
          #   failureThreshold: 3
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          # volumeMounts:
          # - mountPath: /server/UserData
          #   name: trackmania-serverdata
      # volumes:
      #   - name: trackmania-serverdata
      #     persistentVolumeClaim:
      #      claimName: trackmania-serverdata
