ingress-nginx:
  controller:
    ingressClassResource:
      controllerValue: "nginx.org/ingress-controller"
    kind: DaemonSet
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
    2049: external-ingress/truenas:2049
    222: external-ingress/truenas:22
  udp:
    1514: graylog/graylog-syslog-udp:1514
