ingress-nginx:
  controller:
    ingressClassResource:
      controllerValue: "nginx.org/ingress-controller"
    kind: DaemonSet
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
    2049: external-ingress/truenas:2049
    2003: influxdb/influxdb:2003
    2350: trackmania/trackmania:2350
    5000: trackmania/trackmania:5000
    3724: azerothcore/ac-authserver:3724
    8085: azerothcore/ac-worldserver:8085
  udp:
    1514: graylog/graylog-syslog-udp:1514
    2350: trackmania/trackmania:2350
